### PR TITLE
Fix navigation buttons click handling

### LINKED ISSUE #58: Minor gesture navigation conflict
Hi, thanks for working on the app!

Android gesture navigation (swiping from the bottom of the screen) seems to activate one of the three bottom "buttons" (and it shouldn't, obviously).

### PR DESCRIPTION
**Pull request by di72nn**
Fix an issue with unwanted clicks when using gesture navigation.
Fixes #58.

### CODE REVIEW

**Comment by Medvedev91** [comment]
I use motionEventSpy() instead of clickable() because it works much faster in this case.

**Comment by di72nn** [comment]
Well, of course it works faster, but also incorrectly, because it doesn't wait for the motion to finish. And the motion can be [canceled](https://developer.android.com/reference/android/view/MotionEvent#ACTION_CANCEL) (something like that probably happens in the related issue).

Even simpler way to reproduce it is to touch the button, move your finger away from the button, and then release outside of the button. Any normal button doesn't register such events as clicks, but these navigation buttons do.

**Comment by Medvedev91** [comment]
Yes, I know all the side effects. But I'm going by experience of use in each situation. This method worked well for years. 

I'am sure there is a solution for LineageOS. Like 1px bottom padding or something else. I will try to fix that as soon as I get LinageOS.

**Comment by Medvedev91** [comment]
The buttons are placed above the navigation. It's strange that motionEventSpy() is triggered. Perhaps we can also consider this to be a LinageOS bug.

In the worst case, we can make a special modifier for LinageOS.

**Comment by di72nn** [comment]
Now that you mentioned it... I actually have the "navigation hint" (the bar) disabled, so there's zero space for navigation at the bottom. Enabling the "navigation hint" does resolve the issue (at least on crDroid). Maybe LineageOS has broken implementation, I don't have any device to compare (there are other implementations though - e.g., [Samsung](https://x.com/MishaalRahman/status/1751420543293694412)).

**Comment by Medvedev91** [comment]
On my devices it works well even if the bar disabled.

**Comment by Medvedev91** [comment]
Also, I want to say thank you! Glad to see someone managed to understand my code.

: )

**Pull request closed without merging**
